### ISSUE TITLE
Hohe CPU-Last nach Start der Zammadbridge

### ISSUE THREAD

**Issue by Tw133ki** [qmexnetworks/3cx-zammad-bridge#3]
Sobald ich die Zammadbridge starte, habe ich hohe-CPU-last:

![grafik](https://user-images.githubusercontent.com/96547836/151652697-283cc1c3-5990-407e-bce7-1a20ab7b10cd.png)
![grafik](https://user-images.githubusercontent.com/96547836/151652738-c4f1d6d9-21ff-455c-8ec0-774a23cc3880.png)

**Comment by qmex-mp** [comment]
Moin, 
ein paar mehr Infos wären schon praktisch, um was für Hardware handelt es sich? Bzw. auf welche Hardware basiert die VM sofern es sich um eine handelt?
Das die Brücke Last erzeugt ist logisch, diese pollt etwa alle 0,5 Sekunden die API, was aber auch notwendig ist. Dies ist auf normaler Hardware absolut kein Problem:
![image](https://user-images.githubusercontent.com/8076291/151660361-8c103497-e5ab-49ea-a8df-f27d39bdb034.png)

**Comment by Tw133ki** [comment]
Sorry! Ich hab den Fehler gefunden, war Layer-8.
Ich habe ausversehen, den teil mit dem poll-Intervall nicht hinein kopiert. :-(
Danke für die schnelle Antwort.
