### ISSUE TITLE
Feature Request: Filter Calls by inbound number 

### ISSUE THREAD

**Issue by wucherpfennig** [qmexnetworks/3cx-zammad-bridge#8]
This software works as expected, thank you for your efforts!

However we are facing an issue where we would like to "route" one 3cx instance to two dedicated zammad instances. (By its dedicated external number)

With the current implementation a request to zammad only is issued if an active call is connected to an active 3cx extension.

Do you see a possibility to filter the active calls by the inbound external number?

BR wucherpfennig

**Comment by qmex-mp** [comment]
Hi,
we built already something like that on customer request, depending on Call Queues we can trigger different Instances (for this customer even Zendesk).
If there is interest you can give us a call or write a ticket and we look into it: +49 421 377 000 / info@q-mex.net
